#!/usr/bin/env python
# coding: utf-8

from athenah_ai.indexer import AthenahIndexer
from athenah_ai.client import AthenahClient

# prompt: str = "What does the isNewerVersion function return?"
# path: str = "/Users/darkmatter/projects/transia/athena-ai/tests/fixtures/BuildInfo.cpp"
# indexer = AthenahIndexer("local", "id", "dist", "testv1", "v1")
# indexer.index_file(path, "testv1")
# client = AthenahClient("id", "dist", "testv1", "v1")
# response = client.prompt(prompt)
# print(response)

# prompt: str = "What does the isNewerVersion function return?"
# path: str = "/Users/darkmatter/projects/transia/athena-ai/tests/fixtures/BuildInfo.cpp"
# indexer = AthenahIndexer("gcs", "id", "dist", "testv1", "v1")
# indexer.index_file(path, "testv1")
# client = AthenahClient("id", "/tmp", "testv1", "v1")
# response = client.prompt(prompt)
# print(response)

prompt: str = """
```
# XLS-78d - Subscriptions

```
Title:        Subscriptions
Type:         Draft
Revision:     2
Last Update:  06/09/2024
Authors:      Chris Dangerfield @xrpl365
              Denis Angell @angell_denis
```

## Updates

Updated: 06/09/2024

- Adjusted SubscriptionCreate transaction name to SubscriptionSet and added support for updating the Amount and new optional FinalPaymentTime.
- Added support for optional FinalPaymentTime to support fixed length subscriptions.
- SubscriptionCancel updated to support either Account or Recipient being able to cancel.

## Abstract

This proposal introduces a subscription (re-occurring payments) mechanism to the XRP Ledger (XRPL), enabling functionality similar to direct debits, thus removing the need for users to sign a transaction for each payment. The account owner will define values that are used to protect against abuse.

## Motivation and Rationale

Currently, payments on the XRP Ledger require the sender to initiate and sign each transaction. With the introduction of off-chain solutions like Xaman API, the concept of PULL payments emerged, where a transaction can be generated by the destination address and signed by the sender. However, this method still requires the user to authorize each transaction individually, which is not practical for services requiring regular, recurring payments, ie: subscriptions.

This proposal addresses this limitation by introducing a subscription feature that allows for pre-authorized recurring payments, improving the user experience and enabling a broader range of services on the XRP Ledger.

The proposed subscription model is designed to balance user convenience with security. By allowing pre-authorized payments within defined parameters, the system reduces the need for frequent user interaction while maintaining control over the amounts and frequency of payments. This approach also allows businesses to automate billing processes, improving service delivery while ensuring that users retain oversight and control of their recurring payments. The subscription feature enhances the versatility of the XRP Ledger, making it more accommodating for services that rely on automated, regular payments.

This proposal will support both payments in XRP and issued assets.

## Amendment

This feature enables account owners to authorize automated payments with predefined parameters such as amount, frequency, and recipient, reducing the need for manual transaction signing each time.

The amendment adds the following:

- A new ledger entry: `Subscription`
- A new transaction type: `SubscriptionSet`
- A new transaction type: `SubscriptionCancel`
- A new transaction type: `SubscriptionExecute`

### **New Ledger Entry: `Subscription`**

The `Subscription` ledger entry is a new on-ledger object that stores the details of the subscription, including the recipient address, the maximum allowable amount, the frequency of the payments, and the start time of the subscription.

**Fields:**

| Field              | Type      | Required | Description                                                                                                                       |
| ------------------ | --------- | -------- | --------------------------------------------------------------------------------------------------------------------------------- |
| sfAccount          | AccountID | ✔️       | The account that owns the subscription.                                                                                           |
| sfRecipient        | AccountID | ✔️       | The account authorized to receive the subscription payments.                                                                      |
| sfDestinationTag   | Number    |          | Support for subscription payment categorization by the Recipient.                                                                 |
| sfAmount           | Amount    | ✔️       | The subscription amount (max) that can be withdrawn during each time period.                                                      |
| sfFrequency        | UInt64    | ✔️       | The time period (in seconds) between consecutive payments (e.g., 2592000 for monthly).                                            |
| sfNextPaymentTime  | UInt32    | ✔️       | The next time (Ripple epoch time) the payment can be executed. This field is automatically updated after each successful payment. |
| sfFinalPaymentTime | UInt32    |          | The time (Ripple epoch time) of the last payment. Allows for optional fixed period subscriptions.                                 |

**Example `Subscription` object:**

```
{
  "LedgerEntryType": "Subscription",
  "Account": "r9cZA1mLK5R5Am25ArfXFmqgNwjZgnfk59",
  "Recipient": "rLdCa1mLK5R5Am25ArfXFmqgNwjZgnfy91",
  "DestinationTag": 10, // Bob is customer number 10
  "Amount": "100000000", // 100 XRP
  "Frequency": 2592000, // 30 days in seconds
  "NextPaymentTime": 711232800, // (example epoch time for next payment)
  "FinalPaymentTime": 721600800 // (example epoch time for final payment)
}
```

We compute the `Subscription` object ID, a.k.a., SubscriptionID as the SHA-512Half of the following values, concatenated in order:

- The Subscription space key (0x00??)
- The Account ID
- The Recipient ID
- The Txn Sequence

### **New Transaction Type: `SubscriptionSet`**

The `SubscriptionSet` transaction is used to create a new subscription. The account owner specifies the recipient, amount, frequency, and optionally the start time.

**Fields:**

| Field              | Type      | Required | Description                                                                                              |
| ------------------ | --------- | -------- | -------------------------------------------------------------------------------------------------------- |
| sfTransactionType  | String    | ✔️       | The type of transaction:`SubscriptionSet`.                                                               |
| sfAccount          | AccountID | ✔️       | The account that is creating the subscription.                                                           |
| sfRecipient        | AccountID | ✔️       | The account authorized to receive the subscription payments.                                             |
| sfDestinationTag   | Number    |          | A destination tag to be associated with the subscription payment.                                        |
| sfAmount           | Amount    | ✔️       | The subscription amount (max) that can be withdrawn during each time period.                             |
| sfFrequency        | UInt64    | ✔️       | The time period (in seconds) between consecutive payments.                                               |
| sfStartTime        | UInt32    |          | (Optional) The time (Ripple epoch time) when the subscription starts. If not set, it starts immediately. |
| sfFinalPaymentTime | UInt32    |          | (Optional) The time (Ripple epoch time) when the subscription ends.                                      |
| sfSubscriptionID   |           |          | (Optional) Used for updating a subscription.                                                             |

**Example `SubscriptionSet` Transaction (Create):**

```
{
  "TransactionType": "SubscriptionSet",
  "Account": "r9cZA1mLK5R5Am25ArfXFmqgNwjZgnfk59",
  "Recipient": "rLdCa1mLK5R5Am25ArfXFmqgNwjZgnfy91",
  "DestinationTag": 10, // Bob is customer number 10
  "Amount": "100000000", // 100 XRP
  "Frequency": 2592000, // 30 days in seconds
  "StartTime": 711232800, // (example epoch time for start time)
  "FinalPaymentTime": 721600800 // (example epoch time for final payment)
}
```

**Example `SubscriptionSet` Transaction (Update):**

```
{
  "TransactionType": "SubscriptionSet",
  "Account": "r9cZA1mLK5R5Am25ArfXFmqgNwjZgnfk59",
  "Amount": "100000000", // 100 XRP
  "FinalPaymentTime": 724192800, // (example epoch time for final payment increased by one frequency period)
  "SubscriptionID": "E8A6F9B99B041DF5C932DF8DA29B2A84B42D4D4F0F4A08931D76D62F42E1F1B9"
}
```

#### **Failure Conditions** (Create)

- `Recipient` is the same as `Account`.
- `Amount` is invalid OR <= 0.
- `Frequency` <= SYSTEM_MINIMUM (global value defining the minimum frequency: eg 1 hour or 1 day).
- `Subscription` ledger entry exists.
- `Account` does not have a valid Trustline (Limit, Frozen, Auth, Rippling).
- `StartTime` is less than the current time.
- `FinalPaymentTime` is less than the current time.
- `FinalPaymentTime` is less than the `StartTime`.
- `FinalPaymentTime` is less than the `NextPaymentTime`.

#### State Changes (Create)

- Creates the `Subscription` ledger entry, initializing all the fields.
- If the `StartTime` field is included then the `NextPaymentTime` is the `StartTime`.
- If the `StartTime` field is not included then the `NextPaymentTime` is the current ledger time.

#### **Failure Conditions** (Update)

- Subscription Entry `Account` is not the same as the txn `Account`.
- `Amount` is invalid OR <= 0.
- `Subscription` ledger entry does not exists.
- `Account` does not have a valid Trustline (Limit, Frozen, Auth, Rippling).
- `FinalPaymentTime` is less than the current time.
- `FinalPaymentTime` is less than the `StartTime`.
- `FinalPaymentTime` is less than the `NextPaymentTime`.
- `SubscriptionID` submitted and `Amount` not present or optional `FinalPaymentTime` not present.

#### State Changes (Update)

- Updates the `Amount` and `FinalPaymentTime`.

### **New Transaction Type: `SubscriptionCancel`**

The `SubscriptionCancel` transaction is used to cancel an existing subscription. The transaction must be signed by the account that created the subscription.

**Fields:**

| Field             | Type      | Required | Description                                               |
| ----------------- | --------- | -------- | --------------------------------------------------------- |
| sfTransactionType | String    | ✔️       | The type of transaction:`SubscriptionCancel`.             |
| sfAccount         | AccountID | ✔️       | The account that created the subscription.                |
| sfSubscriptionID  | Hash256   | ✔️       | The unique identifier of the subscription to be canceled. |

**Example `SubscriptionCancel` Transaction:**

```
{
  "TransactionType": "SubscriptionCancel",
  "Account": "r9cZA1mLK5R5Am25ArfXFmqgNwjZgnfk59",
  "SubscriptionID": "E8A6F9B99B041DF5C932DF8DA29B2A84B42D4D4F0F4A08931D76D62F42E1F1B9"
}
```

#### **Failure Conditions**

- `SubscriptionID` does not exist.
- `Account` is not the owner of the `Subscription` OR the `Recipient` on the `Subscription`.

#### **State Changes**

- Removes the `Subscription` ledger entry associated with the given `SubscriptionID`.

### **New Transaction Type: `SubscriptionExecute`**

The `SubscriptionExecute` transaction is used by the recipient to pull the funds from the subscriber’s account according to the predefined rules.

**Fields:**

| Field             | Type      | Required | Description                                                                         |
| ----------------- | --------- | -------- | ----------------------------------------------------------------------------------- |
| sfTransactionType | String    | ✔️       | The type of transaction:`SubscriptionExecute`.                                      |
| sfAccount         | AccountID | ✔️       | The account authorized to receive the subscription payment.                         |
| sfSubscriptionID  | Hash256   | ✔️       | The unique identifier of the subscription being executed.                           |
| sfAmount          | Amount    | ✔️       | The amount being pulled, which must be less than or equal to the authorized amount. |

**Example `SubscriptionExecute` Transaction with XRP:**

```
{
  "TransactionType": "SubscriptionExecute",
  "Account": "rLdCa1mLK5R5Am25ArfXFmqgNwjZgnfy91",
  "SubscriptionID": "E8A6F9B99B041DF5C932DF8DA29B2A84B42D4D4F0F4A08931D76D62F42E1F1B9",
  "Amount": "100000000" // 100 XRP
}
```

**Example `SubscriptionExecute` Transaction with issued asset:**

```
{
  "TransactionType": "SubscriptionExecute",
  "Account": "rLdCa1mLK5R5Am25ArfXFmqgNwjZgnfy91",
  "SubscriptionID": "E8A6F9B99B041DF5C932DF8DA29B2A84B42D4D4F0F4A08931D76D62F42E1F1B9",
  "Amount": {
    "currency": "USD",
    "value": "20",
    "issuer": "rUSDIssuerWKDv6jmDy1pUykJzF3wq" // Example issuer
  }
}
```

#### **Failure Conditions**

- Subscription ledger entry does not exist for SubscriptionID.
- `Account` is not the recipient specified in the `Subscription` OR the recipient of the `Subscription`.
- `Amount` is < 0.
- If `Amount` is IOU and IOU is a "bad" currency.
- `Amount` (type) does not equal `Subscription` `Amount` (type).
- `Amount` exceeds the authorized amount in the subscription.
- `Account` has insufficient funds
- `Account` does not have a valid Trustline (Limit, Frozen, Auth, Rippling)
- `Recipient` does not have a valid Trustline (Limit, Frozen, Auth, Rippling) (Optional)
- `Recipient` does not have enough XRP to cover creation of Trustline (Optional)
- Current time is before `NextPaymentTime`.

#### **State Changes**

- Deducts the specified `Amount` from the subscriber’s account.
- Updates `NextPaymentTime` in the `Subscription` ledger entry to the `NextPaymentTime` plus the `Frequency`.
- Credit the specified `Amount` to the recipient account.
- Create `Recipient` Trustline (Optional)
- Removes the `Subscription` ledger object where time > `FinalPaymentTime`.
```

Create all the files and functions required to implement the above proposal. 
"""
client = AthenahClient("id", "/tmp", "Rippled", "v1")
response = client.prompt(prompt)
print(response)
